name: Run linters and tests
on:
  push:
    branches: [main]
    paths-ignore: [.editorconfig, .gitignore, LICENSE, README.md, .github/workflows/release-please.yml]
    tags-ignore: ['*']
  pull_request:
    paths-ignore: [.editorconfig, .gitignore, LICENSE, README.md, .github/workflows/release-please.yml]

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test build
        run: yarn check-types
