name: Release Please
on:
  push:
    branches: [main]

env:
  NODE_VERSION: 16

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          pull-request-title-pattern: 'chore${scope}: release${component} v${version}'
          bump-minor-pre-major: true
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance Improvements"},{"type":"deps","section":"Dependencies"},{"type":"revert","section":"Reverts"},{"type":"docs","section":"Documentation","hidden":true},{"type":"style","section":"Styles","hidden":true},{"type":"chore","section":"Miscellaneous Chores","hidden":true},{"type":"refactor","section":"Code Refactoring","hidden":true},{"type":"test","section":"Tests","hidden":true},{"type":"ci","section":"Continuous Integration","hidden":true}]'

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
